# Site settings
url: ""
baseurl: ""

# Git setup to use the comment section
username: "Whispyy"
reponame: "API-git"

# using font awesome turn it to false if you don't want
font-awesome-include: true

# Build settings
markdown: kramdown

exclude: ["README.md"]

gems:
  - jekyll-seo-tag